#!/usr/bin/env bash
json=`curl -s -S "https://registry.hub.docker.com/v2/repositories/yongjhih/parse-server/tags/"`
while [ "$json" ]; do
    echo "$json" | jq '.results[]["name"]'
    next=`echo "$json" | jq -r '.next'`
    if [[ "$next" && "$next" != "null" ]]; then
        json=`curl -s -S "$next"`
    else
        json=
    fi
done | sort 2> /dev/null
