#!/usr/bin/env bash

image="$1"
appId="${2:-appId}"
masterKey="${3:-mastarKey}"

docker run -it                       \
           -e APP_ID=$appId          \
           -e MASTER_KEY=$masterKey  \
           -p 1337:1337              \
           -p 2022:22                \
           --name parse-server       \
           $image
