#!/usr/bin/env bash

set -e

if [ ! -d ~/.ssh/ ]; then
    mkdir -p ~/.ssh/
fi

if [ ! -d /home/git/.ssh/ ]; then
    mkdir -p /home/git/.ssh/
    touch /home/git/.ssh/authorized_keys
    chown git:git /home/git/.ssh/authorized_keys
fi

while read line; do
  echo "$line" >> ~/.ssh/authorized_keys
  echo "$line" >> /home/git/.ssh/authorized_keys
done
